USE [master]
GO

/****** Object:  Database [TaskDb]    Script Date: 3/30/2020 7:42:15 PM ******/
CREATE DATABASE [TaskDb]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'TaskDb', FILENAME = N'F:\Dotnet Workspace\Task\Database\TaskDb.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'TaskDb_log', FILENAME = N'F:\Dotnet Workspace\Task\Database\TaskDb_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [TaskDb] SET COMPATIBILITY_LEVEL = 130
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [TaskDb].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [TaskDb] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [TaskDb] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [TaskDb] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [TaskDb] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [TaskDb] SET ARITHABORT OFF 
GO

ALTER DATABASE [TaskDb] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [TaskDb] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [TaskDb] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [TaskDb] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [TaskDb] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [TaskDb] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [TaskDb] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [TaskDb] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [TaskDb] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [TaskDb] SET  DISABLE_BROKER 
GO

ALTER DATABASE [TaskDb] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [TaskDb] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [TaskDb] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [TaskDb] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [TaskDb] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [TaskDb] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [TaskDb] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [TaskDb] SET RECOVERY FULL 
GO

ALTER DATABASE [TaskDb] SET  MULTI_USER 
GO

ALTER DATABASE [TaskDb] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [TaskDb] SET DB_CHAINING OFF 
GO

ALTER DATABASE [TaskDb] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [TaskDb] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [TaskDb] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [TaskDb] SET QUERY_STORE = OFF
GO

USE [TaskDb]
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO

ALTER DATABASE [TaskDb] SET  READ_WRITE 
GO

USE [TaskDb]
GO
/****** Object:  Table [dbo].[Task]    Script Date: 5/10/2020 12:07:28 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Task](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Description] [varchar](500) NOT NULL,
	[IsDone] [bit] NOT NULL,
	[IsDelete] [bit] NOT NULL,
	[CreatedDate] [datetime] NOT NULL,
 CONSTRAINT [PK_Tasks] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO